# Generated by Django 5.0.2 on 2024-02-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_total_order_order_total_order_order_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='size',
        ),
    ]
