# Generated by Django 5.0.2 on 2024-02-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderproducts_size'),
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
