# Generated by Django 5.0.2 on 2024-02-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_catecory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('catecory_img', models.ImageField(blank=True, upload_to='photos/catecgories')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'catecgories',
            },
        ),
        migrations.DeleteModel(
            name='Catecory',
        ),
    ]
